name: Build SimpleOS

on:
  push:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and Test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt install build-essential nasm
      
    - name: Build Project
      run: make floppy
